import { Prisma } from "@/generated/prisma/client";
import { ConflictError, ForbiddenError, NotFoundError } from "@/lib/errors";
import { AttendanceRepository } from "@/repositories/attendance.repository";
import type { AttendanceActor, AttendanceRecordInput, AttendanceRecordUpdateInput, AttendanceSearchQuery, AttendanceSessionListQuery, CreateAttendanceSessionInput } from "@/types/attendance";
import { createLogger } from "@/utils/logger";

const logger = createLogger({ service: "AttendanceService" });
export class AttendanceService {
  constructor(private readonly repository = new AttendanceRepository()) {}
  async createSession(input: CreateAttendanceSessionInput, actor: AttendanceActor) { return this.mapErrors(async () => { const session = await this.repository.createSession(input, actor); if (!session) throw new NotFoundError("Eligible section"); logger.info("Attendance Session Created", { ...actor, sessionId: session.id }); return this.sessionResponse(session); }); }
  async getSession(id: string, actor: AttendanceActor) { const session = await this.repository.findSession(id, actor); if (!session) throw new NotFoundError("Attendance session"); return this.sessionResponse(session); }
  async listSessions(query: AttendanceSessionListQuery, actor: AttendanceActor) { const result = await this.repository.listSessions(query, actor); return { items: result.items.map((item) => this.sessionResponse(item)), total: result.total, totalPages: Math.ceil(result.total / query.pageSize), currentPage: query.page }; }
  async dashboard(sessionDate: Date, actor: AttendanceActor) { const section = await this.repository.findDashboardSection(actor); if (!section) return { section: null, session: null, roster: [] }; const session = await this.repository.findSessionBySectionDate(section.id, sessionDate, actor); const roster = await this.repository.findRoster(section.id, sessionDate, session?.id); return { section, session: session ? this.sessionResponse(session) : null, roster: roster.map((entry) => ({ enrollmentId: entry.id, name: [entry.student.lastName, entry.student.firstName, entry.student.middleName].filter(Boolean).join(", "), sex: entry.student.sex, attendance: entry.attendanceRecords[0] ?? null })) }; }
  async reopenSession(id: string, actor: AttendanceActor) { this.requireAdmin(actor); return this.mapErrors(async () => { const session = await this.repository.reopenSession(id, actor); if (!session) throw new ConflictError("Attendance session is not finalized or is unavailable."); logger.info("Attendance Session Reopened", { ...actor, sessionId: id }); return this.sessionResponse(session); }); }
  async record(sessionId: string, input: AttendanceRecordInput, actor: AttendanceActor) { this.assertSource(input); await this.requireOpenSession(sessionId, actor); return this.mapErrors(async () => { const record = await this.repository.createRecord(sessionId, input, actor); if (record === false) throw new NotFoundError("Eligible enrollment"); if (!record) throw new ConflictError("Attendance session is finalized or unavailable."); logger.info("Attendance Recorded", { ...actor, sessionId, enrollmentId: input.enrollmentId }); return record; }); }
  async updateRecord(id: string, input: AttendanceRecordUpdateInput, actor: AttendanceActor) { this.assertSource(input); const sessionId = await this.recordSession(id); await this.requireOpenSession(sessionId, actor); return this.mapErrors(async () => { const record = await this.repository.updateRecord(id, input, actor); if (!record) throw new ConflictError("Attendance session changed state. Retry the request."); logger.info("Attendance Updated", { ...actor, recordId: id }); return record; }); }
  async deleteRecord(id: string, actor: AttendanceActor) { this.requireAdmin(actor); const sessionId = await this.recordSession(id); await this.requireOpenSession(sessionId, actor); return this.mapErrors(async () => { if (!await this.repository.deleteRecord(id, actor)) throw new ConflictError("Attendance session changed state. Retry the request."); logger.info("Attendance Deleted", { ...actor, recordId: id }); return { id }; }); }
  async finalize(id: string, actor: AttendanceActor) { await this.requireOpenSession(id, actor); return this.mapErrors(async () => { const session = await this.repository.finalizeSession(id, actor); if (!session) throw new ConflictError("Attendance session changed state. Retry the request."); logger.info("Attendance Session Finalized", { ...actor, sessionId: id }); return this.sessionResponse(session); }); }
  async records(id: string, query: AttendanceSearchQuery, actor: AttendanceActor) { await this.getSession(id, actor); const result = await this.repository.listRecords(id, query); return { ...result, totalPages: Math.ceil(result.total / query.pageSize), currentPage: query.page }; }
  async summary(id: string, actor: AttendanceActor) { await this.getSession(id, actor); const grouped = await this.repository.summary(id); return grouped.reduce((summary, item) => ({ ...summary, [item.status.toLowerCase()]: item._count._all }), { present: 0, late: 0, absent: 0, excused: 0 }); }
  private async requireOpenSession(id: string, actor: AttendanceActor) { const session = await this.getSession(id, actor); if (session.state !== "OPEN") throw new ConflictError("Attendance session is finalized."); return session; }
  private async recordSession(id: string) { const record = await this.repository.findRecord(id); if (!record) throw new NotFoundError("Attendance record"); return record.attendanceSessionId; }
  private requireAdmin(actor: AttendanceActor) { if (actor.role !== "ADMIN") throw new ForbiddenError("Only administrators can perform this operation."); }
  private assertSource(input: { source: string; scannedAt?: Date | null }) { if (input.source === "MANUAL" && input.scannedAt) throw new ConflictError("Manual attendance cannot include a scan timestamp."); if (["QR_SCAN", "NFC_SCAN", "BIOMETRIC"].includes(input.source) && !input.scannedAt) throw new ConflictError("Scanned attendance requires a scan timestamp."); }
  private sessionResponse<T extends { status: string }>(session: T) { return { ...session, state: session.status === "DRAFT" ? "OPEN" : "FINALIZED" }; }
  private async mapErrors<T>(operation: () => Promise<T>) { try { return await operation(); } catch (error) { this.throwAttendanceError(error); } }
  private throwAttendanceError(error: unknown): never { if (error instanceof Prisma.PrismaClientKnownRequestError) { if (error.code === "P2002") throw new ConflictError("Attendance already exists for this session or section date."); if (error.code === "P2003") throw new NotFoundError("Referenced attendance resource"); if (error.code === "P2025") throw new NotFoundError("Attendance resource"); if (error.code === "P2034") throw new ConflictError("Attendance operation conflicted with another request. Retry the request."); } throw error; }
}
export const attendanceService = new AttendanceService();
