import { AttendanceSessionStatus, Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/prisma";
import type { AttendanceActor, AttendanceRecordInput, AttendanceRecordUpdateInput, AttendanceSearchQuery, AttendanceSessionListQuery, CreateAttendanceSessionInput } from "@/types/attendance";

const retryLimit = 3;
const sessionSelect = { id: true, sectionId: true, sessionDate: true, status: true, finalizedAt: true, finalizedById: true, section: { select: { name: true, gradeLevel: true, adviserId: true } } } satisfies Prisma.AttendanceSessionSelect;
const recordSelect = { id: true, status: true, source: true, scannedAt: true, notes: true, enrollmentId: true, attendanceSessionId: true, enrollment: { select: { student: { select: { id: true, lrn: true, firstName: true, middleName: true, lastName: true } } } } } satisfies Prisma.AttendanceRecordSelect;

export class AttendanceRepository {
  async createSession(input: CreateAttendanceSessionInput, actor: AttendanceActor) { return this.serializable(async (tx) => { const section = await tx.section.findFirst({ where: this.sectionWhere(input.sectionId, actor), select: { id: true } }); if (!section) return null; return tx.attendanceSession.create({ data: { ...input, createdById: actor.actorId, updatedById: actor.actorId }, select: sessionSelect }); }); }
  async findSession(id: string, actor: AttendanceActor) { return prisma.attendanceSession.findFirst({ where: { id, section: this.sectionWhere(undefined, actor) }, select: sessionSelect }); }
  async listSessions(query: AttendanceSessionListQuery, actor: AttendanceActor) { const where: Prisma.AttendanceSessionWhereInput = { section: this.sectionWhere(query.sectionId, actor), ...(query.sessionDate ? { sessionDate: query.sessionDate } : {}), ...(query.schoolYearId ? { section: { ...this.sectionWhere(query.sectionId, actor), schoolYearId: query.schoolYearId } } : {}) }; const [items, total] = await prisma.$transaction([prisma.attendanceSession.findMany({ where, select: sessionSelect, orderBy: [{ sessionDate: "desc" }, { id: "asc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.attendanceSession.count({ where })]); return { items, total }; }
  async findDashboardSection(actor: AttendanceActor) { return prisma.section.findFirst({ where: this.sectionWhere(undefined, actor), select: { id: true, name: true, gradeLevel: true }, orderBy: [{ gradeLevel: "asc" }, { name: "asc" }] }); }
  async findSessionBySectionDate(sectionId: string, sessionDate: Date, actor: AttendanceActor) { return prisma.attendanceSession.findFirst({ where: { sectionId, sessionDate, section: this.sectionWhere(undefined, actor) }, select: sessionSelect }); }
  async findRoster(sectionId: string, sessionDate: Date, sessionId: string | undefined) { return prisma.enrollment.findMany({ where: this.eligibleEnrollmentWhere(undefined, sectionId, sessionDate), select: { id: true, student: { select: { firstName: true, middleName: true, lastName: true, sex: true } }, attendanceRecords: { where: { attendanceSessionId: sessionId ?? "00000000-0000-0000-0000-000000000000" }, select: { id: true, status: true, scannedAt: true }, take: 1 } }, orderBy: [{ student: { lastName: "asc" } }, { id: "asc" }] }); }
  async findRecord(id: string) { return prisma.attendanceRecord.findUnique({ where: { id }, select: { id: true, attendanceSessionId: true } }); }
  async listRecords(sessionId: string, query: AttendanceSearchQuery) {
    const tokens = query.search?.split(/\s+/).filter(Boolean) ?? [];
    const where: Prisma.AttendanceRecordWhereInput = { attendanceSessionId: sessionId, ...(query.status ? { status: query.status } : {}), ...(tokens.length ? { enrollment: { student: { AND: tokens.map((token) => ({ OR: [{ lrn: { contains: token, mode: "insensitive" } }, { firstName: { contains: token, mode: "insensitive" } }, { middleName: { contains: token, mode: "insensitive" } }, { lastName: { contains: token, mode: "insensitive" } }] })) } } } : {}) };
    const [records, total] = await prisma.$transaction([prisma.attendanceRecord.findMany({ where, select: recordSelect, orderBy: [{ enrollment: { student: { lastName: "asc" } } }, { id: "asc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.attendanceRecord.count({ where })]);
    return { records, total };
  }
  async createRecord(sessionId: string, input: AttendanceRecordInput, actor: AttendanceActor) { return this.serializable(async (tx) => { const session = await tx.attendanceSession.findFirst({ where: { id: sessionId, status: AttendanceSessionStatus.DRAFT, section: this.sectionWhere(undefined, actor) }, select: { sectionId: true, sessionDate: true } }); if (!session) return null; const enrollment = await tx.enrollment.findFirst({ where: this.eligibleEnrollmentWhere(input.enrollmentId, session.sectionId, session.sessionDate), select: { id: true } }); if (!enrollment) return false; return tx.attendanceRecord.create({ data: { attendanceSessionId: sessionId, enrollmentId: enrollment.id, status: input.status, source: input.source, notes: input.notes, scannedAt: input.scannedAt, recordedById: actor.actorId, updatedById: actor.actorId }, select: recordSelect }); }); }
  async updateRecord(id: string, input: AttendanceRecordUpdateInput, actor: AttendanceActor) { return this.serializable(async (tx) => { const record = await tx.attendanceRecord.findFirst({ where: { id, attendanceSession: { status: AttendanceSessionStatus.DRAFT, section: this.sectionWhere(undefined, actor) } }, select: { id: true } }); if (!record) return null; return tx.attendanceRecord.update({ where: { id: record.id }, data: { ...input, updatedById: actor.actorId }, select: recordSelect }); }); }
  async deleteRecord(id: string, actor: AttendanceActor) { return this.serializable(async (tx) => { const record = await tx.attendanceRecord.findFirst({ where: { id, attendanceSession: { status: AttendanceSessionStatus.DRAFT, section: this.sectionWhere(undefined, actor) } }, select: { id: true } }); if (!record) return null; return tx.attendanceRecord.delete({ where: { id: record.id }, select: { id: true } }); }); }
  async finalizeSession(id: string, actor: AttendanceActor) { return this.serializable(async (tx) => { const session = await tx.attendanceSession.findFirst({ where: { id, status: AttendanceSessionStatus.DRAFT, section: this.sectionWhere(undefined, actor) }, select: { id: true, sectionId: true, sessionDate: true } }); if (!session) return null; const enrollments = await tx.enrollment.findMany({ where: this.eligibleEnrollmentWhere(undefined, session.sectionId, session.sessionDate), select: { id: true } }); await tx.attendanceRecord.createMany({ data: enrollments.map((enrollment) => ({ attendanceSessionId: id, enrollmentId: enrollment.id, status: "ABSENT", source: "FINALIZATION", recordedById: actor.actorId, updatedById: actor.actorId })), skipDuplicates: true }); return tx.attendanceSession.update({ where: { id }, data: { status: AttendanceSessionStatus.FINALIZED, finalizedAt: new Date(), finalizedById: actor.actorId, updatedById: actor.actorId }, select: sessionSelect }); }); }
  async reopenSession(id: string, actor: AttendanceActor) { return this.serializable(async (tx) => { const session = await tx.attendanceSession.findFirst({ where: { id, status: AttendanceSessionStatus.FINALIZED, section: this.sectionWhere(undefined, actor) }, select: { id: true } }); if (!session) return null; return tx.attendanceSession.update({ where: { id: session.id }, data: { status: AttendanceSessionStatus.DRAFT, finalizedAt: null, finalizedById: null, updatedById: actor.actorId }, select: sessionSelect }); }); }
  async summary(sessionId: string) { return prisma.attendanceRecord.groupBy({ by: ["status"], where: { attendanceSessionId: sessionId }, _count: { _all: true } }); }
  private sectionWhere(id: string | undefined, actor: AttendanceActor): Prisma.SectionWhereInput { return { ...(id ? { id } : {}), deletedAt: null, schoolYear: { status: "ACTIVE", deletedAt: null }, ...(actor.role === "TEACHER" ? { adviserId: actor.actorId } : {}) }; }
  private eligibleEnrollmentWhere(id: string | undefined, sectionId: string, date: Date): Prisma.EnrollmentWhereInput { return { ...(id ? { id } : {}), sectionId, enrolledOn: { lte: date }, OR: [{ endedOn: null }, { endedOn: { gte: date } }], student: { deletedAt: null } }; }
  private async serializable<T>(operation: (transaction: Prisma.TransactionClient) => Promise<T>): Promise<T> { for (let attempt = 0; attempt < retryLimit; attempt += 1) { try { return await prisma.$transaction(operation, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (error) { if (!this.isConflict(error) || attempt === retryLimit - 1) throw error; await new Promise((resolve) => setTimeout(resolve, 20 * (attempt + 1) + Math.floor(Math.random() * 20))); } } throw new Error("Retry loop ended unexpectedly."); }
  private isConflict(error: unknown) { return error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2034"; }
}
